### ISSUE TITLE
Date is off by 24105600 seconds

### ISSUE THREAD

**Issue by kiliankoe** [fsr/infoscreen#15]
![img_0376](https://cloud.githubusercontent.com/assets/2625584/6103621/93c382bc-b046-11e4-85a3-9e61fa0d5352.JPG)

**Comment by kiliankoe** [comment]
Or do I add them together for 1+1=2?

**Comment by jgonsior** [comment]
Monate als Binärzahlen sind sicherlich ein Feature.
Aber so in Ernst, braucht man das Datum da überhaupt? Ansonsten schmeißt man es einfach aus dem Code komplett raus :laughing:

**Comment by dirkonet** [comment]
Seriously, JavaScript? 1+1=11? … meh. Possibly fixed in 1e68be17.
