### ISSUE TITLE
Weather information

### ISSUE THREAD

**Issue by kiliankoe** [fsr/infoscreen#19]
@hoodie just wished for this (if there's space left)

**Comment by hoodie** [comment]
http://forecast.io/#/f/51.0536,13.7408

**Comment by kiliankoe** [comment]
We can gladly use the same forecast API key as matthias for this.

**Comment by h4llow3En** [comment]
Implemented in middelware in fdbfc7efc9441d4d8141974f7e8fbc83365b20a5 fronted needs to be done as well
