### ISSUE TITLE
Four departures per stop

### ISSUE THREAD

**Issue by dirkonet** [fsr/infoscreen#20]
Please show 4 departures per stop in `new_version` so we know when the next bus/tram will come for both directions. I kind of got used to that in the old version.

**Comment by Feliix42** [comment]
This has actually been implemented more than a week ago but we haven't found the time to adjust the design to the four stops yet (this week are holidays...). But we are on it!

**Comment by dirkonet** [comment]
Seems to be fixed. Thanks.
