### ISSUE TITLE
Weather warnings from Deutscher Wetterdienst

### ISSUE THREAD

**Issue by horazont** [fsr/infoscreen#22]
Data is available e.g. here: http://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json

(that’s the JSONP they use for the website; I do not know whether there’s any kind of official API)

filtering can happen either via data["warnings"][*][*]["regionName"] == "Stadt Dresden", or by figuring out the numeric key for dresden (update: that should be `114612000`, if I understood the SVG on the website correctly, needs to be verified when dresden has warnings again) when there is a current warning. data["vorabInformation"] has the same structure as data["warnings"], but contains only preliminary information and no actual warnings; might be sensible to show these while there are no warnings available.

**Comment by kiliankoe** [comment]
A red (as in eye-catching) overlay somewhere on the screen whenever there are actual warnings would be pretty cool. I usually receive them as push notifications on my phone and the last few days have been pretty full of them :D 
I'd say not showing anything regarding DWD data when no warnings are available though.

**Comment by horazont** [comment]
The non-warnings in the vorabInformation should be shown I think. Maybe not as prominent, but if they warn about thunderstorms, it is a nice-to-know, because they will usually be converted to an actual warning later on.

Also, it might make sense to filter heat and frost warnings; those are not as relevant for most and will be plenty in the summer/winter. Those could also be shown, but not as prominent as e.g. a thunderstorm or heavy rain warning.

**Comment by kiliankoe** [comment]
If we just go with relevant information it might even be a better idea to take some other weather source and display an approximate minute countdown until it rains.

**Comment by h4llow3En** [comment]
Implemented in middelware in fdbfc7efc9441d4d8141974f7e8fbc83365b20a5 fronted needs to be done as well

**Comment by h4llow3En** [comment]
Weather is implemented, Warnings won't be shown
