### ISSUE TITLE
Anzeigezeit für FSR-News runter setzen

### ISSUE THREAD

**Issue by kalinni** [fsr/infoscreen#25]
Stand heute sehr lange vor dem Infoscreen und wollte mir die git-Workshop-News ansehen - nach 5 Minuten wurde aber immer noch die nächste Sitzung angekündigt. Die News sollten schneller weiterschalten. Aber so, wie ich den Code lese, müsste das eigentlich auch alle 20 Sekunden passieren, oder?
Was ist da kaputt?
(Und ja, ich bin sicher, dass noch mehr News als die zur Sitzung existierten...)

**Comment by tocsinDE** [comment]
Laut https://github.com/fsr/infoscreen/blob/new_version/frontend/assets/src/InfoScreen.js#L37 wechseln die News alle 10 Minuten. Könnte man meiner Meinung nach definitiv runtersetzen. 5 Minuten fände ich auch vernünftig.

**Comment by h4llow3En** [comment]
Die news werden alle 10 Minuten gewechselt
Es ist der "new_version" branch deployed. Und dort wird es im Javascript refreshed

**Comment by kalinni** [comment]
Oh, ok, dann hab ich an der falschen Stelle im Code gesucht. Ich finde 5 Minuten immer noch unsinnig. 15 Sekunden fände ich gut! Oder von mir aus 20. Aber länger braucht man niemals zum lesen der Infos, die auf den vorhandenen Platz passen!

**Comment by h4llow3En** [comment]
Es kann auch schon mal ein längerer Text sein. Und die allgemeine Meinung war, dass 10 Minuten eine gute Zeit wären.
Selbst 2 Minuten finde ich persönlich doch schon ziemlich kurz, wenn es beispielsweise eine news ist, die den ganzen Block einnimmt.

**Comment by kiliankoe** [comment]
Zeit mit der Wortanzahl dynamisch berechnen?

**Comment by h4llow3En** [comment]
Gerne, auch wenn es im Moment erst mal wichtiger ist, dass wir wieder Bilder anzeigen können.

**Comment by kiliankoe** [comment]
Aber 10 ist schon echt hart. Als absolutes Maximum würde ich auch einfach mal 2 vorschlagen, auch wenn man da gefühlt schon echt lange am Warten ist.

**Comment by kalinni** [comment]
Üblicherweise kommt doch aber auf den Newsscreen kein riesen langer Text, das ist die absolute Ausnahme. Der zum git-Workshop wurde von Julius auch entsprechend auf wenige Sätze gekürzt. Wer mehr wissen will, schaut auf die Website, auf den Infoscreen soll immer ne Kurzfassung, ich meine, das hatten wir sogar mal so entschieden. Und wenn du 20 Sekunden bevor der Text rum ist, anfängst zu lesen, wartest du so Ewigkeiten, bis du weiter lesen kannst. Wenn alles nur kurz angezeigt wird, liest du auch mal alle News. Wenn du aber ne halbe Stunde da rumstehen muss, nur um ein Spieleabendplakat, das Cyberspaceplakat und das Datum der nächsten Sitzung zu sehen, ist das doch völlig bescheuert. Ich hab heute davor festgestellt WIE lang ne Minute sein kann....

**Comment by kalinni** [comment]
Philipp ist für ne Gestenerkennung und die Möglichkeit, per Handgeste weiter zu blättern. Das wäre super. :D

**Comment by sjmielke** [comment]
(...und wenn jemand, der nicht wie ein Informatiker aussieht, davor steht, wird das ZIH Video angezeigt? :P )
Ne, ernsthaft, < 30s ist mMn Pflicht. Das schöne an kurzen Intervallen ist ja eben, dass man alles mal kurz sieht und wenn mans nicht schafft, zu Ende zu lesen, hey, in einer Minute isses wieder da.

**Comment by h4llow3En** [comment]
Das hatte ich auch schon mal vorgeschlagen, da waren nur alle der Meinung, dass zu viele Menschen dann einfach vor dem Fenster rumhampeln würden

**Comment by jgonsior** [comment]
Ich wäre auch für so 15-20 Sekunden. Die news auf dem infoscreen sind doch sowieso meistens nicht mehr als ein/zwei Sätze, und wenn doch sollte man das meiner Meinung nach auf ein/zwei Sätze runterkürzen.
