### ISSUE TITLE
Last part of headline gets truncated in the backend form

### ISSUE THREAD

**Issue by jgonsior** [fsr/infoscreen#26]
I just created an entry with the headline **Frag Absolventen beim "All You Can Ask"**. If I want to edit this entry later on I only see **Frag Absolventen beim** in the input form in the backend, everything between the double quotes isn't shown there. I guess it could be fixed by using htmlspecialchars() or so?

**Comment by Feliix42** [comment]
Perhaps out :php: man @sjmielke or @tocsinDE can have a look at this? My PHP knowledge is relatively limited. ^^
