### ISSUE TITLE
Hide stale data

### ISSUE THREAD

**Issue by dirkonet** [fsr/infoscreen#27]
The current implementation of the infoscreen does not hide stale data or give any indication that the departures currently shown are outdated. Please either hide the departures if there was no contact to the server for x minutes or show the time of the last data update – both of these were included in the old version by the way ;)

**Comment by kiliankoe** [comment]
This is already mentioned in #21 if I'm not mistaken. Not that the functionality exists, but still^^

**Comment by dirkonet** [comment]
I was pretty sure I already mentioned this and somehow didn't see the previous issue when looking for it. Well.
