### ISSUE TITLE
Ingress Portal Status

### ISSUE THREAD

**Issue by heisig** [fsr/infoscreen#8]
Display the portal status of the "*Kunst*" as a colored indicator

**Comment by dirkonet** [comment]
If someone wants to go ahead and implement this, http://ingress.42.vc/portal.php?id=0 gives you the state for Datenautobahn, http://ingress.42.vc/portal.php?id=1 the state for the Skulptur. ENL/RES/GRY/UNK. Only works from FSR office LAN, currently updates not too often.

**Comment by kiliankoe** [comment]
Alter... Wie?? :D

**Comment by dirkonet** [comment]
ENL - Enlightened/Green
RES - Resistance/Blue
GRY - Neutral/Grey/Gray ;)
UNK - what do I know?

**Comment by kiliankoe** [comment]
Oh, I thought UNK was somehow meaning uncaptured... Nvm then.

**Comment by dirkonet** [comment]
The backend/API now updates the state of our two portals every 10 minutes. Please adapt the frontend accordingly :)
